# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc7e1eef5c7dfd1b45b7a4ff21bc1cbdd86fdaf220f20fb5e98f65921432f5b465ba0b66416ad6089f7f73e96a889efcbdbcd6345b8c6bf7151ec2341cdc66c9

test:
  secret_key_base: f6ffc1af90c65e94e1a23b2acccebcc0ea8a4ec004e9c126f750cb94ebcbf8b5052c95f7a0aa35dc168e3394f46211d9498a2ac74bdca8722519ce2e817b5a68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
